############### SERVER CONFIG #############
server:
  port: 9002
  ssl:
    key-store: classpath:localhost.jks
    key-store-password: changeit
    key-alias: localhost
    
############### DATABASE CONFIG ##############
spring:
    datasource:  
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:XE
      username: springboot
      password: admin  