############### SERVER CONFIG #############
server:
  contextPath: /
  port: 9002
  ssl:
    key-store: classpath:certificate/localhost.jks
    key-store-password: changeit
    key-alias: localhost
    
    
    
    
############### DATABASE CONFIG ##############
#spring:
#    jpa:#      database-platform: org.hibernate.dialect.Oracle10gDialect#      show-sql: true
#    datasource:  
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@localhost:1521:XE
#      username: projectdb
#      password: admin
#

spring:
  jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa         
 