############### DATABASE CONFIG ##############
spring:
  security:    user:      name: admin
      password: admin  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa     
    