spring:
  security:
    saml2:
      relyingparty:
        registration:
          okta:
           assertingparty:
              metadata-uri: https://dev-05406312.okta.com/app/exkapgdwa05bM8oS15d7/sso/saml/metadata
           signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"